### ISSUE TITLE
Add --target support

### ISSUE THREAD

**Issue by iggy** [ilteoood/docker_buildx#10]
It would be nice if this supported the build(x) option `--target`. I currently use a multi-stage Dockerfile to build each tag from a single file (the first stage installs all the deps/etc, so it makes sense to use one Dockerfile). Then I build like so:

```
docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t iggy/image1:latest --target stage1 --pull --push .
docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t iggy/image2:latest --target stage2 --pull --push .
```

**Comment by ilteoood** [comment]
Done with the latest version!
