### ISSUE TITLE
Dockerfile true none false 

### ISSUE THREAD

**Issue by asdaragon** [ilteoood/docker_buildx#12]
my yml file [Build Image.yml](https://github.com/AragonSnow/qiandao/blob/master/.github/workflows/Build%20Image.yml)
when i use it ,it is not work.this logs:
```
actions_builder
#1 [internal] booting buildkit
#1 pulling image moby/buildkit:buildx-stable-1
#1 pulling image moby/buildkit:buildx-stable-1 1.5s done
#1 creating container buildx_buildkit_actions_builder0
#1 creating container buildx_buildkit_actions_builder0 1.7s done
#1 DONE 3.2s
Supported platforms:  linux/amd64, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6
WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
"docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.

Usage:  docker buildx build [OPTIONS] PATH | URL | -

Start a build
##[error]Command failed: docker_buildx/scripts/docker_build.sh linux/arm64,linux/amd64 ***/qiandao latest Dockerfile true none false 
```
how can i solve it?

**Comment by ilteoood** [comment]
Hi,
can you retry please?

**Comment by asdaragon** [comment]
> Hi,
> can you retry please?

i have retried many times. but the problem go on.
 
![_L7GH{K 5VG18@(MENEGDUA](https://user-images.githubusercontent.com/22835918/82440649-44b76980-9acf-11ea-97cb-ec716d2d1516.png)

**Comment by ilteoood** [comment]
Is your project public?

**Comment by ilteoood** [comment]
I see that your last try was 7 hours ago, I fixed it 4 hours ago, more or less.
Can you please re-trigger it?

**Comment by ilteoood** [comment]
I tried with my unique image and everything goes fine:
https://github.com/ilteoood/docker-surfshark/runs/692708794

**Comment by bogn83** [comment]
@AragonSnow @ilteoood for me quite a similar error occured. The only difference in my case was: `true none false` appeared as `true   false` with an additional empty space in between (gets removed by GitHub display logic). I could boil it down to the script not supporting empty args properly currently. Thus I've added the following patch to [index.js#L45](https://github.com/ilteoood/docker_buildx/blob/439099796bfc03dd9cedeb72a0c7cb92be5cc92c/index.js#L45) and then it worked for me with or without empty build args:
```patch
-    parameters = (parameters || []).join(' ');
+    parameters = (parameters || []).map(i => i === '' ? "''" : i).join(' ');
```

You can find it in PR #13.

**Comment by ilteoood** [comment]
Hi @bogn83 ,
can you show me your workflow, the one with which you had the error?
