### ISSUE TITLE
Could you add build context or workdir to allow building images from subdirs

### ISSUE THREAD

**Issue by krasi-georgiev** [ilteoood/docker_buildx#14]
At the moment it runs in the root directory and if the dockerfile references files with relative path the build fails. 

This can be solved like

```
docker buildx build --platform $1 $PUSH $LOAD $TAGS $BUILD_ARGS $TARGET -f $4 .
```
change into
```
docker buildx build --platform $1 $PUSH $LOAD $TAGS $BUILD_ARGS $TARGET $4
```

and probably rename arg $4 from docker file into buildContext

**Comment by ilteoood** [comment]
Sorry for the big delay, I completely forgot this issue.
It has been implemented, with version 1.0.5
