### ISSUE TITLE
How do you make the build manually?

### ISSUE THREAD

**Issue by ncw** [ilteoood/docker_buildx#19]
This is a stupid question!

The recent rclone release 1.54.1 didn't run the publish action for some reason as yet unknown, so rclone's docker image didn't get built.

I'd like to run it manually, but I can't figure out how - is there some way I can use the code from this action to do it?

I know how to make a normal docker build and upload it but I can't figure out how to use the extra magic here to create more architectures manually.

Thanks

**Comment by ilteoood** [comment]
Hi @ncw,
you can run the [install_buildx.sh](https://github.com/ilteoood/docker_buildx/blob/master/scripts/install_buildx.sh) starting from `# Confiure buildx` comment.

After that you build the image in the same way, but using `docker buildx build` instead of `docker build`

**Comment by ncw** [comment]
Thank you - those instructions worked very well. I understand how it works a lot better now :-)
