### ISSUE TITLE
Build Step withholds logs until it finishes

### ISSUE THREAD

**Issue by zmingxie** [ilteoood/docker_buildx#2]
The current bash shell implementation withholds the logs until the build step finishes. This is not ideal especially when `buildx` could be running multi-arch builds in parallel.

Looking at another docker-builx github action (https://github.com/crazy-max/ghaction-docker-buildx), and it doesn't have this issue. Perhaps this will be an easy fix?

**Comment by ilteoood** [comment]
Hi,
I did a quick edit from my phone. Can you make a test using the master branch?

**Comment by zmingxie** [comment]
Your fix indeed works! Then I noticed one more issue, and I've created a PR for it: https://github.com/ilteoood/docker_buildx/pull/3

Closing this one now.
