### ISSUE TITLE
Error failed to solve: rpc error: code = Unknown desc = server message: insufficient_scope: authorization failed

### ISSUE THREAD

**Issue by vabene1111** [ilteoood/docker_buildx#7]
So when trying to use this action to buld a docker image the build fails with the follwing error message:

```

#31 pushing layers
#31 pushing layers 0.3s done
#31 ERROR: server message: insufficient_scope: authorization failed
------
 > exporting to image:
------
failed to solve: rpc error: code = Unknown desc = server message: insufficient_scope: authorization failed
##[error]Command failed: docker_buildx/scripts/docker_build.sh linux/amd64,linux/arm64,linux/arm/v7 recipes test Dockerfile true none
```

The full log can be found [here](https://github.com/vabene1111/recipes/runs/583462534), the action file in question is [this one](https://github.com/vabene1111/recipes/blob/develop/.github/workflows/docker-release-publish.yml).

I have searched for the error message and have found various issues [1](https://github.com/docker/buildx/issues/202) [2](https://github.com/docker/buildx/issues/101) but have not been able to fix this.

Any ideas on what could be causing this issue ? Thanks very much in advance!

**Comment by ilteoood** [comment]
Hi, I think that the image name isn't valid for the docker standards.
Did you tried with YOUR_DOCKER_HUB_NAME/recipes?

**Comment by vabene1111** [comment]
a i could have thought of that .. not the most helpful of error messages but that isn't your fault.

Thank you very much for your assistance!

**Comment by clearloop** [comment]
https://github.com/docker/build-push-action/issues/301
